### ISSUE TITLE
[P3.5][Mac] apio upload breaks

### ISSUE THREAD

**Issue by ameyec** [FPGAwars/apio#147]
Hi,

Working in macos X Sierra. 
Using apio 0.3.0
And an IceStick

Everything seems to work until I do an upload:

```
$ apio upload
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/apio", line 11, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/apio/commands/upload.py", line 41, in cli
    drivers.pre_upload()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/apio/managers/drivers.py", line 115, in pre_upload
    self._pre_upload_darwin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/apio/managers/drivers.py", line 223, in _pre_upload_darwin
    if self._check_ftdi_driver_darwin(driverA):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/apio/managers/drivers.py", line 237, in _check_ftdi_driver_darwin
    return driver in subprocess.check_output(['kextstat'])
TypeError: a bytes-like object is required, not 'str'
```

Still, listing the ftdi devices does show my icestick:

```
$ apio system --lsftdi
Number of FTDI devices found: 1
Checking device: 0
Manufacturer: Lattice, Description: Lattice FTUSB Interface Cable
```
I did have an issue before so I could get there, so I had to see issue #143 :

```
export SCONS_LIB_DIR=/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scons-3.0.1
```

**Comment by Jesus89** [comment]
Hi! It seems to be a Python 3.5 issue. The function `subprocess.check_output` returns a bytes-like object in Python 3.5. I think a`str` could solve the issue.

Could you update apio with `pip install -U git+git://github.com/fpgawars/apio.git` and try again?

Thanks.
