### ISSUE TITLE
Error when executing the command apio install --system in Linux-64

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#31]
Apio has been installed in a virtualenv
The error message is:

```
$ apio install --system
Traceback (most recent call last):
  File "/home/obijuan/venvs/pio1/bin/apio", line 11, in <module>
    sys.exit(cli())
  File "/home/obijuan/venvs/pio1/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/obijuan/venvs/pio1/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/obijuan/venvs/pio1/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/obijuan/venvs/pio1/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/obijuan/venvs/pio1/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/obijuan/venvs/pio1/local/lib/python2.7/site-packages/apio/__init__.py", line 64, in install
    SystemInstaller().install()
  File "/home/obijuan/venvs/pio1/local/lib/python2.7/site-packages/apio/packages/system.py", line 20, in __init__
    self.version = self._get_version()
  File "/home/obijuan/venvs/pio1/local/lib/python2.7/site-packages/apio/packages/system.py", line 54, in _get_version
    version = releases['tag_name'].split('.')[1]  # v0.X -> X
KeyError: 'tag_name'
```
Apio version:
```
$ apio --version
apio, version 0.0.5
```

**Comment by Jesus89** [comment]
Fixed: added release in old url: https://github.com/bqlabs/tools-usb-ftdi/releases.
Also new url will be updated in new versions.
